- name: configure mysql server
  host: mysql
  become: yes
  tasks:
  - name: Install mysql
   ansible.builtin.package:
    name: mysql
    state: present

- name: enable mysql server
   ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.daws82s.online
    register: mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "MySQL info: {{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }} "
    when: mysql_info.failed is true